declare const classNames: {
  readonly "app-shell": "app-shell";
  readonly "app-topbar": "app-topbar";
  readonly "app-topbar__left": "app-topbar__left";
  readonly "app-topbar__right": "app-topbar__right";
  readonly "brand-mark": "brand-mark";
  readonly "brand-mark__img": "brand-mark__img";
  readonly "app-tabs": "app-tabs";
  readonly "app-tabs__item": "app-tabs__item";
  readonly "app-tabs__item--active": "app-tabs__item--active";
  readonly "app-tabs__indicator": "app-tabs__indicator";
  readonly "app-tabs--indicator-hidden": "app-tabs--indicator-hidden";
  readonly "app-icon-button": "app-icon-button";
  readonly "app-icon-button--active": "app-icon-button--active";
  readonly "app-content": "app-content";
  readonly "update-modal__content": "update-modal__content";
  readonly "update-modal__copy": "update-modal__copy";
  readonly "update-modal__versions": "update-modal__versions";
  readonly "update-modal__version-card": "update-modal__version-card";
  readonly "update-modal__label": "update-modal__label";
  readonly "update-modal__version": "update-modal__version";
  readonly "update-modal__notes": "update-modal__notes";
  readonly "update-modal__status": "update-modal__status";
  readonly "update-modal__actions": "update-modal__actions";
};
export = classNames;
