[package]
name = "ayphr-firmware"
version = "0.1.0"
edition = "2021"

[package.metadata.esp-idf-sys]
esp_idf_tools_install_dir = "global"
esp_idf_sdkconfig_defaults = ["sdkconfig.defaults"]

[dependencies]
esp-idf-svc = { version = "0.52.1", features = ["critical-section"] }
esp-idf-sys = { version = "0.37.2", features = ["binstart"] }
esp32-nimble = "0.12.0"
embedded-hal = "1.0"
bme280-multibus = "0.5"
log = "0.4"
anyhow = "1.0"

ayphr-protocol = { path = "../shared" }

[build-dependencies]
embuild = "0.33.2"

[profile.dev]
panic = "abort"
opt-level = "s"

[profile.release]
panic = "abort"
opt-level = "s"
